import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import {BsFillMoonStarsFill} from "react-icons/bs"
import {useState} from "react"
import {AiFillLinkedin, AiFillInstagram , AiFillGithub, AiFillMail} from "react-icons/ai"
import deved from "../../public/dev-ed-wave.png"

import design from "../../public/design.png"
import code from "../../public/code.png"
import consulting from "../../public/consulting.png"

export default function Home() {
  const [darkmode, setDarkMode] = useState(false);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
          <section className="min-h-screen pt-10 pb-32">
            <nav className="flex justify-between">
              <h1 className="text-xl font-burtons dark:text-white">developyed</h1>
              <ul className="flex items-center">
                <li className="dark:text-teal-600">
                  <BsFillMoonStarsFill className="cursor-pointer text-2xl"  onClick={() => setDarkMode(!darkmode)}/></li>
                <li>
                  <a className="bg-gradient-to-r  from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-lg ml-8" href="#">
                    Resume</a></li>
              </ul>
            </nav>

            <div className="text-center pt-20 md:pt-24 lg:pt-28">
              <h2 className={styles.name}>Meyzan Al Yutra</h2>
              <h2 className={styles.devanddesig}>Developer and designer</h2>
              <p className="text-medium leading-8 text-gray-800 sm:text-xl max-w-2xl mx-auto dark:text-white">
                Freelancer providing services for programming and design content needs</p>
            </div>

            <div className="mt-10 lg:mt-8 text-4xl gap-6 flex flex-wrap justify-center text-gray-500 dark:text-white">
                <AiFillLinkedin className={styles.logososmed} />
                <AiFillInstagram  className={styles.logososmed}/>
                <AiFillGithub className={styles.logososmed}/>
                <AiFillMail className={styles.logososmed}/>
            </div>

            
            <div className="mt-10 lg:mt-8 relative bg-gradient-to-b from-teal-500 rounded-full 
              w-60 h-60  mx-auto overflow-hidden lg:w-[16rem] lg:h-[16rem]">
              <Image
                // loader={deved}
                src={deved}
                alt="Picture of the author"
              />
            </div>

          </section>
          
        <section className="pb-16">
            <div>
              <h3 className="text-3xl py-1 font-medium dark:text-white">
                Services I offer
              </h3>
              <p className="text-md py-2 leading-6 text-gray-800 dark:text-white">
                since the beginning of my journey as a freelance
                <span className="text-teal-500"> agencies</span> consulted for <span className="text-teal-500"> startups</span>  and collaborated with talanted people to create digital 
                products for both business and cunsumer use
              </p>
            </div>
            <div className="lg:flex gap-6">
                <div className="p-10 my-10   rounded-lg shadow-xl text-center   hover:bg-teal-500 group dark:bg-white dark:hover:bg-teal-500 ">
                  <Image src={design}  width={100} height={100} alt="design" className="mx-auto" />
                  <h3 className="text-lg font-medium pt-8 pb-2    group-hover:text-white">Beutiful Designs</h3>
                  <p className="py-2 group-hover:text-white">Creating elegant designs suited for your needs design theory</p>
                  <h4 className=" text-teal-500 group-hover:text-white">Design tools I use</h4>
                  <p className="text-gray-800 mt-2 group-hover:text-white">React</p>
                  <p className="text-gray-800 mt-2 group-hover:text-white">Figma</p>
                  <p className="text-gray-800 mt-2 group-hover:text-white">Tailwind</p>
                </div>

                <div className="text-center shadow-xl p-10 rounded-lg my-10  hover:bg-teal-500 group dark:bg-white dark:hover:bg-teal-500 ">
                  <Image src={code}  width={100} height={100} alt="design" className="mx-auto" />
                  <h3 className="text-lg font-medium pt-8 pb-2  group-hover:text-white">Beutiful Designs</h3>
                  <p className="py-2 group-hover:text-white">Creating elegant designs suited for your needs design theory</p>
                  <h4 className="text-teal-500 group-hover:text-white">Design tools I use</h4>
                  <p className="text-gray-800 mt-2 group-hover:text-white">React</p>
                  <p className="text-gray-800 mt-2 group-hover:text-white">Figma</p>
                  <p className="text-gray-800 mt-2 group-hover:text-white">Tailwind</p>
                </div>
            
                <div className="text-center shadow-xl p-10 rounded-lg my-10 hover:bg-teal-500 group dark:bg-white dark:hover:bg-teal-500">
                  <Image src={consulting}  width={100} height={100} alt="design" className="mx-auto" />
                  <h3 className="text-lg font-medium pt-8 pb-2">Beutiful Designs</h3>
                  <p className="py-2  group-hover:text-white">Creating elegant designs suited for your needs design theory</p>
                  <h4 className="text-teal-500  group-hover:text-white">Design tools I use</h4>
                  <p className="text-gray-800 mt-2  group-hover:text-white">React</p>
                  <p className="text-gray-800 mt-2  group-hover:text-white">Figma</p>
                  <p className="text-gray-800 mt-2  group-hover:text-white">Tailwind</p>
                </div>

            </div>
        </section>
      </main>
    </>
  )
}
